site_name: My Project Docs

site_description: Documentation for the My Project Docs.

site_author: Your Name

repo_url: https://github.com/<your-username>/<your-repository>

theme:
  name: material
  palette:
    primary: blue
    accent: light-blue
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate

plugins:
  - search

nav:
  - Home: index.md
  - Project Overview: project-overview.md
  - Project Vision: project-vision.md
  - Project Objectives: project-objectives.md
  - Stakeholders: stakeholders.md
  - Product Overview: product-overview.md
  - Product Backlog Building: product-backlog-building.md
  - MVPs: mvp.md
  - Software Development Process: project-lifecycle.md
  - Project Roadmap: roadmap.md
  - Workflow: workflow.md
  - Issue Tracking & Task Management: issue-tracking.md
  - Project Deliverables: deliverables.md
  - Meeting Minutes: meetings.md
  - Lessons Learned: lessons-learned.md
  - References: references.md
  - External Tools & Dependencies: tools.md
  - API Documentation: api.md
  - System Architecture: architecture.md
  - Database Schema: database-schema.md
  - Setup Guides:
    - MkDocs Configuration: setup/mkdocs-configuration.md
    - MkDocs Setup: setup/mkdocs-setup.md
    - Publishing Guide: setup/publishing-guide.md
    - Python Virtual Environment Setup: setup/python-venv-setup.md
    - README: setup/readme.md

extra:
  analytics:
    provider: google
    property: UA-XXXXX-Y

strict: true
use_directory_urls: true
