theme:
  name: material
  palette:
    primary: black
    accent: red
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate
    - toc.collapse

site_name: MkDocs Example Project

site_description: This is a sample project documentation site built using MkDocs.

site_author: Lucas Antunes

repo_url: https://github.com/LucasGSAntunes/DOCS_Example


plugins:
  - search

nav:
  - Home: index.md
  - Project:
      - Overview: project/overview.md
      - Vision & Objectives:
          - Project Vision: project/vision-objectives/vision.md
          - Project Objectives: project/vision-objectives/objectives.md
      - Stakeholders: project/stakeholders.md
      - Product:
          - Product Overview: project/product/overview.md
          - Product Backlog: project/product/product-backlog-building.md
          - MVPs:
              - MVP 1-2025: project/product/mvps/mvp_2025_1.md
              - MVP 2-2025: project/product/mvps/mvp_2025_2.md
  - Management:
      - Roadmap: project/management/roadmap.md
      - Workflow: project/management/workflow.md
      - Issue Tracking & Task Management: project/management/issue-tracking.md
      - Project Deliverables: project/management/deliverables.md
      - Meeting Minutes: project/management/meetings.md
      - Lessons Learned: project/management/lessons-learned.md
  - Development Process:
      - Software Development Lifecycle: project/development/lifecycle.md
      - Criteria: project/development/criteria.md
      - Technical Documentation:
          - API Documentation: project/development/technical/api.md
          - System Architecture: project/development/technical/architecture.md
          - Database Schema: project/development/technical/database-schema.md
      - Tools & Dependencies: project/development/tools.md
  - Setup & Configuration:
      - MkDocs:
          - MkDocs Configuration: setup/mkdocs-configuration.md
          - MkDocs Setup: setup/mkdocs-setup.md
      - Environment Setup:
          - Python Virtual Environment: setup/python-venv-setup.md
          - Publishing Guide: setup/publishing-guide.md
      - README: setup/readme.md
  - References: references.md


extra:
  analytics:
    provider: google
    property: UA-XXXXX-Y

strict: true
use_directory_urls: true
